### ISSUE TITLE
博主，你的程序忘了写完了

### ISSUE THREAD

**Issue by artwork771** [zoujingli/ThinkAdmin#101]
项目下载下来顶部只有一个后台首页，
而，商城管理，微信管理，系统管理都没有，而查看代码view也只给出了后台首页。
demo的演示倒是完整的。

另外\application\admin\controller\Plugs.php，
\extend\service\FileService.php里面都有一个函数sysconf（）没有定义，找了好半天都没找到定义在哪里，请告知一下sysconf是什么

**Comment by artwork771** [comment]
![default](https://user-images.githubusercontent.com/32791037/39028755-f1e19538-448a-11e8-99d5-ebc6d6d260b4.JPG)
![2](https://user-images.githubusercontent.com/32791037/39028756-f22938ca-448a-11e8-98ef-bc2257ea8ae9.JPG)
![Uploading 捕获3.JPG…]()
![Uploading 捕获4.JPG…]()

**Comment by artwork771** [comment]
![3](https://user-images.githubusercontent.com/32791037/39028821-517723aa-448b-11e8-895f-f258ebd92eb7.JPG)
![4](https://user-images.githubusercontent.com/32791037/39028822-51b2d0bc-448b-11e8-91c8-67361d6a5bef.JPG)

**Comment by zoujingli** [comment]
sysconf
在是框架主函数里定义的

**Comment by zoujingli** [comment]
common.php sysconf
