### ISSUE TITLE
你好，请问带参数的地址添加菜单是怎样填写呢

### ISSUE THREAD

**Issue by sunlaile** [zoujingli/ThinkAdmin#102]
/shop/BookingNews/index?cate_id=9
 这样填写，最后面会自动加.html，导致获取参数值时出错

/shop/BookingNews/index/cate_id/9
这种格式又无法获取参数值

请问怎样处理好呢？谢谢

**Comment by qindj** [comment]
/shop/BookingNews/index.html?cate_id=9

这样写，我这里保存后会变成
/slaughter/log/type.html?id=4.html

直接在LogController的type方法里通过input('id')获取就可以了

**Comment by sunlaile** [comment]
你好，其实我说的获取参数值出错指的是获取不到想要的值，需要二次处理
如 /slaughter/log/type.html?id=4.html
input('id') 获取的值是4.html，而不是4

**Comment by qindj** [comment]
我也是做二次处理，把后面的.html去除掉，不知道有没有更好的方法

**Comment by zoujingli** [comment]
是可以用的
如： 菜单地址：admin/user/index/1
控制器： public function index($type){
// $type 就是对就的1
}
