### ISSUE TITLE
表单验证可以说详细点吗

### ISSUE THREAD

**Issue by freechen** [zoujingli/ThinkAdmin#109]
你好，请教表单验证相关的用法。
1、是不是layui本身的验证机制不能再用了，如自定义验证规则等
2、ret中获取的数据是表单中的元素的值，是一串字符串一样的数据，这个如何使用
3、有没有实际验证的参考代码，文档中写的太简单了

以下是你文档中的表述：

> $.vali 通用表单验证插件
> 
> // 手动实现表单验证
> $(html表单选择器).vali(function(ret){
> 	console.log(ret); // 通过验证后获取的数据
> });
> 
> // 初始化自动表单验证
> $.vali.listen();

**Comment by zoujingli** [comment]
可以使用layui，$.vali 与 layui 不是一样的机制，只要表单上不加 data-auto ，就可以自定义表单处理
