### ISSUE TITLE
图片存储地址，带上了域名是怎么考虑的

### ISSUE THREAD

**Issue by freechen** [zoujingli/ThinkAdmin#113]
图片存储的地址，目前存储的是绝对地址，连域名都存进去了，这怎么考虑的，如果换域名什么的很不方便。

**Comment by zoujingli** [comment]
兼容qiniu oss

**Comment by freechen** [comment]
那本地的能否考虑不存入域名，或者本地存储那能设置存不存入域名。

**Comment by zoujingli** [comment]
https://gitee.com/zoujingli/Think.Admin/blob/master/extend/service/FileService.php#L157
改成false

**Comment by freechen** [comment]
谢谢。

**Comment by freechen** [comment]
去掉ture之后，上传的图片多了一个\
![image](https://user-images.githubusercontent.com/5688949/40886068-1750da8a-6764-11e8-89a5-17ffc4a75dc6.png)

**Comment by zoujingli** [comment]
已经修正路径
