### ISSUE TITLE
修改收货人信息中的收货省市区 能否默认显示 请选择

### ISSUE THREAD

**Issue by freechen** [zoujingli/ThinkAdmin#121]
目前直接显示了北京，不太合理

![image](https://user-images.githubusercontent.com/5688949/40655691-b7e0fb18-6374-11e8-9d5a-ebada528fa88.png)

**Comment by freechen** [comment]
考虑到有些地方应用可能是选填呢，最好能考虑加一个请选择

**Comment by freechen** [comment]
必填如果是默认给了一个，那就没有验证了，误操作的话就直接写入了默认的了。我觉得不应该有默认的。

**Comment by zoujingli** [comment]
订单的收货信息是必需的

**Comment by zoujingli** [comment]
前台必然会提交过来
