### ISSUE TITLE
依赖使用发布的版本而不是master分支

### ISSUE THREAD

**Issue by huangzhhui** [zoujingli/ThinkAdmin#131]
`composer.json` 内的 ` "zoujingli/ip2region": "dev-master"`和`"zoujingli/weopen-developer": "dev-master"`不要使用 `dev-master` ，应该使用已发布的版本，同时发布在 packagist.org ，否则每次 `composer install or update` 都要到 Github 下载，速度很慢

**Comment by zoujingli** [comment]
已经处理
