### ISSUE TITLE
basicAdmin的list翻页依然存在url追加问题。

### ISSUE THREAD

**Issue by poemail** [zoujingli/ThinkAdmin#134]
list翻页在点击页码时依然存在不停的追加url的问题，这个追加足够长时，浏览器是不支持的，直接报错。

Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server.

追加url示例：

/admin.html#/admin/Resources/import.html?%252Fadmin%252FResources%252Fimport_html=&%2525252Fadmin%2525252FResources%2525252Fimport_html=&%25252525252Fadmin%25252525252FResources%25252525252Fimport_html=&%252525252525252Fadmin%252525252525252FResources%252525252525252Fimport_html=&%2525252525252525252Fadmin%2525252525252525252FResources%2525252525252525252Fimport_html=&%25252525252525252525252Fadmin%25252525252525252525252FResources%25252525252525252525252Fimport_html=&spm=m-18-25-27&page=7

**Comment by zoujingli** [comment]
_list 方法 
```php
$url = url('@admin') . '#' . $this->request->baseUrl() . '?' . urldecode(http_build_query($query));
```

**Comment by zoujingli** [comment]
主要考虑 `urldecode(http_build_query($query))`处理
