### ISSUE TITLE
请问这个框架是如何封装的，我想知道布局是怎么实现的？

### ISSUE THREAD

**Issue by xiaomengceo** [zoujingli/ThinkAdmin#135]
框架是如何把单个控制器的内容加载进框架然后显示出来的？我也想学学做一个框架

**Comment by xiaomengceo** [comment]
我只会用iframe框架加载，你这个什么原理呀？大神可以赐教吗？

**Comment by qindj** [comment]
【非官方】
简单的说放一个div，id叫content，然后点击菜单，通过ajax调取后台数据，放到这个content里，替换旧内容，结束

**Comment by zoujingli** [comment]
上面说的正确，异步内容区加载

**Comment by xiaomengceo** [comment]
> 
> 
> 【非官方】
> 简单的说放一个div，id叫content，然后点击菜单，通过ajax调取后台数据，放到这个content里，替换旧内容，结束
谢谢知道，大致懂了，ajax'居然可以这样用，很巧妙呀！
