### ISSUE TITLE
URL中的#是怎样配置的，能否去掉，变成标准的pathinfo

### ISSUE THREAD

**Issue by helloyht** [zoujingli/ThinkAdmin#137]
当前是： http://localhost/thinkAdmin/admin.html#/thinkAdmin/admin/index/main.html?spm=m-7

后一个thinkAdmin多余

请问怎样变成 http://localhost/thinkAdmin/admin.html/admin/index/main.html?spm=m-7

**Comment by zoujingli** [comment]
不行，这个单页路由，必需带上。
不然需要改布局
