### ISSUE TITLE
权限管理不规范

### ISSUE THREAD

**Issue by miwei230** [zoujingli/ThinkAdmin#164]
建议群主参考 RBAC 规范实现权限管理，将‘访问授权’这里改成权限树的形式，子角色可以再创建新角色。很多项目可能对权限管理没有那么严，只设置一级就可以了。但还是有些项目需要严格控制权限的。

**Comment by zoujingli** [comment]
这个权限是严格控制的，节点那里配置的
权限授权节点时，是节点展示的
