### ISSUE TITLE
建议thinkadmin插件化

### ISSUE THREAD

**Issue by miwei230** [zoujingli/ThinkAdmin#165]
建议thinkadmin 像宝塔面板一样插件化，thinkamdin只留基本管理功能。像微信管理，支付管理，商城、这些都可以插件化。比如使用think-addons,让开发者选择性去安装自己需要的功能。而群主只需要安心开发插件就好，如果可以还可以将插件收费下载。同时也鼓励更多的开发者加入插件市场，集众人智慧让thinkadmin强大起来。不然总是众口难调，每个人都有不同的业务逻辑，不同诉求。所以给群主建议多而繁杂。如果插件化，就可以避免这些问题。

**Comment by zoujingli** [comment]
有这个考虑，不过这个框架适合做二开，太插件化了也不太好
