### ISSUE TITLE
又要给群主找麻烦啦。

### ISSUE THREAD

**Issue by miwei230** [zoujingli/ThinkAdmin#168]
发现这个几个问题：
1、plugs.js 299 行 的zIndex 设置太高了会和文本编辑器冲突，建设设置成  zIndex:99
2、_form.prototype.modal 模态框里的‘保存’和‘关闭’按钮位置应该固定起来，否则数据多了，还得往下滚动。 建议使用layui官方的按钮，修改弹窗如下：
   layer.open({
                type: 1,
                area: ['800px', '80%'],
                resize:true,
                Boolean:true,
                content: res,
                title: title || '',
                zIndex:99, //太高会遮住编辑器,
                success: function (dom, index) {
                    // 此窗口完成时需要自动关闭
                    $.msg.addAutoSuccessCloseIndex(index);
                    var $container = $(dom);
                    /* 事件重载 */
                    $.form.reInit($container);
                },
                btnAlign: 'c',
                btn: ['确定', '取消'],
                yes: function (index, layero) {
                    //点击确认触发 iframe 内容中的按钮提交
                    var form = layero.find(".layui-form");
                    form.submit();  
                }
            });
//当然底部按钮的样式也得去修改下

**Comment by zoujingli** [comment]
感谢反馈，可以提供下你使用的分支版本吗？

**Comment by miwei230** [comment]
1.0和 部分2.0。 因为那时用的富文档编辑器是百度的uedior。 点击uedior的工具按钮的时候，会被luayi遮罩给盖住。后来的ckedit没有这个问题了。

**Comment by zoujingli** [comment]
ueditor问题很多，这个要根据实现情况下调整，现在新版本都是 ck 来做的
