### ISSUE TITLE
提几个比较大众的建议

### ISSUE THREAD

**Issue by WongYueKeung** [zoujingli/ThinkAdmin#174]
用了ThinkAdmin一段时间了，挺不错的得先夸一下你6666
然后想说几个我觉得比较重要的建议。
我觉得后台真的还差这两个功能，就算是实用了！

1，在添加商品的商品内容那里，需要加一个切换设置商品内容的模板的分组，额就是像现在已经有的商品规格分组那种。

因为很多的商城前台的商品介绍里正常都会有一个产品参数这么一个东西:
![image](https://user-images.githubusercontent.com/14259765/55762766-5d1f1d00-5aa3-11e9-9469-e7b742eaac77.png)
或者这样(右半边)：
![image](https://user-images.githubusercontent.com/14259765/55762932-24cc0e80-5aa4-11e9-8b9d-bee14b08bb18.png)
如果写在商品图文里是不合适的，每次新建商品时都要重复写，写在图文里我们不好单独提取出来，也没办法拿去做商品搜索结果页的过滤功能。

所以在输入商品内容哪里，除了输入简单的图文，还需要能够设置比较复杂的商品内容，就是像商品规格分组那样，在做一个选择商品内容的模板的分组。比如说在设置商品内容的模板的分组那里，让我们可以设置无限的键名，然后我们在输入商品内容的时候，除了写图文，还能在选一个商品内容的模板，把值填上就好了。

2.添加商品图片时，允许给每一张加文字

很多商城前台在显示商品图片是有配图片的文字的，比如说明这张图片时商品正面照，如果我们把图片放在商品内容是时没有七牛云静态文件加速的，还很耗数据库。。。

给添加商品图片那里，给每一张图片加个文本框把，这样如果加了很多图片也好区分。。

最后还有一个可能就是补充一下手册，给点例子比如怎么加菜单，加表单内容，设置对话框，前后端具体怎么交互的一个流程，给一个空白、演示构建表格，表单菜单的模板
然后也说一下数据是怎么从于数据库是怎么于前端表单存取的，你的想法都挺厉害的，但是我们希望你写一下基本实现的方法，比如你没有用模型啊这种，然后也有些人和我一样不会VUE.js，对前端不太了解，需要你给一个上手快的手册
我基本上是看完了你所有代码(本人有大概用了两年TP5.1)才知道该怎么在页面里改或者加东西

谢谢啦，看了麻烦给个回馈

**Comment by zoujingli** [comment]
非常感谢您的反馈。
第一点：商品参数会考虑加上，原定义微信商城，做的比较简单，后面会好好完善。
第二点：富文本图片也是基于系统文件，会自己分布上发CDN（根据配置），多图也可以改，不难的。
第三点：开发文档这个还是有点难，主要是精力有限，没时间来弄这个，有空了还是会搞的尤其是4.0

**Comment by yangweijie** [comment]
6点0 都出了 为什么没文档，至少把新功能任务里的进度控制介绍一下啊

**Comment by zoujingli** [comment]
html 绑定行为：data-queue=URL data-confirm=提示内容。
script 直接调用：$.loadQueue(CODE)，这里传 任务编号可以显示前端进度。
控制器直接处理：$this->_queue 方法可以直接处理并返回对应数据，与前端 $.loadQueue 及 data-queue 组合。
后台任务，分两种（指令任务，标准任务）：
指令任务：需要继承 \think\admin\Command 使用 $this->setQueueProgress 设置任务进度。
标准任务，需要继承 \think\admin\service\QueueService 使用 $this->progress 设置任务进度。
【当前返回消息以  javascript: 开头时，会执行 href= 消息内容，以执行脚本指令】
创建任务之后可能获取任务编号，返回给前端。

详情参照微信粉丝同步功能

**Comment by zoujingli** [comment]
v6 任务有重大更新，可以了再解下
前端 data-queue，后端 $this->_queue() 可实现任务进度兼听与事件交互

**Comment by adiudiuu** [comment]
大佬有没有考虑过用vue吗

**Comment by sfss5362** [comment]
大佬有没有考虑过用vue吗

**Comment by biiiiiigmonster** [comment]
后台权限的注解以后会用到php8的源生注解吗

**Comment by zoujingli** [comment]
只要 TP的版本不需要兼容 php7，就会上 php8 注释

> 后台权限的注解以后会用到php8的源生注解吗

**Comment by zoujingli** [comment]
请关注下插件 Wemall 更新。
