### ISSUE TITLE
admin_v4.sql中system_menu导入不上

### ISSUE THREAD

**Issue by beill** [zoujingli/ThinkAdmin#176]
admin_v4.sql导入时候system_menu表导入不成功，单独执行提示Index column size too large. The maximum column size is 767 bytes.，索引值过大

**Comment by ohmyga** [comment]
admin_v4.sql 中搜索 ROW_FORMAT = Compact; 删除掉就可以或者替换为 ROW_FORMAT = DYNAMIC;
mysql默认为DYNAMIC行格式可以支持3072字节     Compact 是不行的。

**Comment by zoujingli** [comment]
新版本不指定 Compact

**Comment by zoujingli** [comment]
已经处理，另外与 mysql 版本有关，推荐 5.5
