### ISSUE TITLE
启动消息任务守护进程失败，提示 “message queue daemon creation failed, try again later!”

### ISSUE THREAD

**Issue by thinkif** [zoujingli/ThinkAdmin#179]
刚刚接触本项目，十分喜欢，在使用的过程中发现这个情况，不知道如何处理了。

执行 php think xtask:start 启动消息任务守护进程，执行后得到信息：
message queue daemon creation failed, try again later!

操作系统： Windows 2008r2
PHP版本：php-7.2.11

实在是没搞清楚应该如何处理。请求帮助。

**Comment by zoujingli** [comment]
windows2008没有测试wmic,可以试试 `php think queue:listen`
