### ISSUE TITLE
在php 5.6.27下面的错误

### ISSUE THREAD

**Issue by im286er** [zoujingli/ThinkAdmin#189]
在5.6.27， apache 下
vendor\topthink\think-helper\src\helper.php
这个文件大概是233行附近的function 后面的类型，会出错
    function trait_uses_recursive(string $trait): array

Parse error: syntax error, unexpected ':', expecting '{' in 
ThinkAdmin\vendor\topthink\think-helper\src\helper.php on line 233

包括下面的几个函数，都会报错，应该是5.6不支持的这种特性吧，
算是小bug

**Comment by zoujingli** [comment]
这个是ThinkPHP组件的bug，我这边修改不了，看看能不能修改下compoesr.json中对应组件的版本号
