### ISSUE TITLE
守护进程只能开启一个，不知道如何对应多个不同队列名

### ISSUE THREAD

**Issue by yangweijie** [zoujingli/ThinkAdmin#190]
rt 只能一个队列的话 性能差 肯定有要求及时的和不及时的

**Comment by zoujingli** [comment]
默认只支持一个

**Comment by zoujingli** [comment]
这里主要考虑到 windows 与 linux 兼容，目前只考虑单进程模式。
后面会考虑使用多进程去处理，不过可能需要加载php组件，也会放弃 think-queue，需要自己开发一个异步任务组件。还请日后继续关注 ThinkAdmin 系列开源作品。感谢！！！

**Comment by yangweijie** [comment]
自己修改了xtask 然后区分线上线下环境 默认不同的队列名 实现 了同服务器 启动不同进程 开发环境 和正式环境队列互不干扰
