### ISSUE TITLE
thinkadmin可以集成不是layui官方的模块formSelects嘛

### ISSUE THREAD

**Issue by seizeMiss** [zoujingli/ThinkAdmin#191]
在实际使用过程中，需要使用到下拉多选框，thinkadmin使用的是layui，官方没有下拉多选框的组件，但是有人做了模块叫做formSelects，有人集成到这个thinkadmin的项目中了嘛？我花了好久都没能集成成功，出现莫名其妙的错误，本人对js了解不深，用到的requireJS也没有了解过，希望有大佬集成过的可以提供帮助，谢谢！

**Comment by zoujingli** [comment]
我也有尝试过，也没有成功。失败的原因可能有：
一、ThinkAdmin 后台为单页程序，某些插件没有做对象销毁处理，再创建会报错。
二、LayUI的插件本身存在问题，大部分会第三方个人开发，建议转用 jQuery 系统插件。

**Comment by sunlaile** [comment]
确实，我也尝试过，不成功
