### ISSUE TITLE
怎么引入vue报错，报vue no defined

### ISSUE THREAD

**Issue by cc2415** [zoujingli/ThinkAdmin#192]
引入vue报错，我已经在admin.js已经引入了

**Comment by zoujingli** [comment]
可以加载的，require 之后会返回 vue 对象
![image](https://user-images.githubusercontent.com/4349951/62817594-e175cf80-bb6b-11e9-89e5-89476e618f8e.png)

**Comment by zoujingli** [comment]
具体可以了解下 cmd 加载机制，基于 requirejs

**Comment by cc2415** [comment]
好的，谢谢。已经解决了
