### ISSUE TITLE
微信对接公众号那里可以了，但是一直找不到图文推送

### ISSUE THREAD

**Issue by cc2415** [zoujingli/ThinkAdmin#194]
![image](https://user-images.githubusercontent.com/23351624/63011742-7c97dd80-bebb-11e9-89ec-a186bcea9bad.png)

这个

**Comment by cc2415** [comment]
![image](https://user-images.githubusercontent.com/23351624/63012041-18294e00-bebc-11e9-8a19-94ae576933ae.png)

**Comment by zoujingli** [comment]
v4，v5 已经不再支持推送功能
