### ISSUE TITLE
ThinkAdmin有没有一种功能，就是批量操作的时候，可以弹出框，而不是直接请求后台的？

### ISSUE THREAD

**Issue by seizeMiss** [zoujingli/ThinkAdmin#195]
如题目，查看官方文档，如果批量是data-update和data-action配套，而弹出层是data-model，能将data-update和data-action结合起来吗，批量操作实现弹出框，输入内容，然后保存。有大神知道这个功能吗？

**Comment by zoujingli** [comment]
需要自己写js去实现
