### ISSUE TITLE
单张图片麻烦也加上删除功能

### ISSUE THREAD

**Issue by freechen** [zoujingli/ThinkAdmin#196]
目前是单张图片上传后，想去掉就去不掉了，只能替换
![image](https://user-images.githubusercontent.com/5688949/63483049-a8bfe980-c4cd-11e9-8e3a-8b0f106eb8e5.png)

**Comment by zoujingli** [comment]
感谢，后面会加上

**Comment by zoujingli** [comment]
v6 已经添加
