### ISSUE TITLE
克隆到本地执行 build.cmd报错，项目无法正常启动

### ISSUE THREAD

**Issue by DickLicha** [zoujingli/ThinkAdmin#198]
![image](https://user-images.githubusercontent.com/21870645/63920994-8b15f580-ca74-11e9-9987-3c515a694e20.png)
![image](https://user-images.githubusercontent.com/21870645/63921009-95d08a80-ca74-11e9-90db-23d6769a34a1.png)
php的ban版本是5.6.69

**Comment by DickLicha** [comment]
请问这个问题改如何解决

**Comment by zoujingli** [comment]
环境安装下依赖扩展，重新build.cmd
