### ISSUE TITLE
多表查询，多个表有相同名称字段，equal应该怎么指定

### ISSUE THREAD

**Issue by plamYuan** [zoujingli/ThinkAdmin#199]
有2个表，
user表（id，user_name，class_id,status）
class（id，class_name，status）
$this->_query(‘user’)->->alias('t1') ->->leftJoin('class t2', 't1.classs_id = t2.id')->equal('status')

这样会报错：'status' in where clause is ambiguous
改为 ->equal('t1.status')  同样报错
请问应该怎么指定

**Comment by zoujingli** [comment]
可以使用别名，如果 equal('t1.status#t1_status')
