### ISSUE TITLE
部署到linux上，图片上传失败

### ISSUE THREAD

**Issue by DickLicha** [zoujingli/ThinkAdmin#201]
centos+nginx部署，上传图片的时候回报 405 not allow，
![image](https://user-images.githubusercontent.com/21870645/65015586-85fde500-d954-11e9-8b52-b8ffc38ac9f0.png)
请问这个该如何解决

**Comment by zoujingli** [comment]
405 像是权限问题，修改下 public/upload 目录权限

**Comment by DickLicha** [comment]
> 405 像是权限问题，修改下 public/upload 目录权限

我把项目所有文件夹都设置成 777权限了还是报一样的问题

**Comment by zoujingli** [comment]
可以提供下测试地址吗?

**Comment by DickLicha** [comment]
可以的这个是地址
 http://39.108.69.198/admin

**Comment by zoujingli** [comment]
服务器执行更新下：
`php think xsync:admin`
`php think xsync:plugs`

**Comment by zoujingli** [comment]
另外修改目录权限用
`chown www:www -R public/upload`

**Comment by zoujingli** [comment]
已经可以了

**Comment by DickLicha** [comment]
嗯嗯，十分感谢确实可以了。你更新了什么文件

**Comment by zoujingli** [comment]
可能是 plupload 在IP访问时的问题，后面做了调整，去除了 plupload 插件，直接使用了 layui 的上传组件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "DickLicha"<notifications@github.com&gt;; 
发送时间: 2019年9月17日(星期二) 下午2:46
收件人: "zoujingli/ThinkAdmin"<ThinkAdmin@noreply.github.com&gt;; 
抄送: "Anyon"<zoujingli@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zoujingli/ThinkAdmin] 部署到linux上，图片上传失败 (#201)




嗯嗯，十分感谢确实可以了。你更新了什么文件

**Comment by DickLicha** [comment]
哦，感谢
