### ISSUE TITLE
你的代码中的ThinkAdmin.exe这个文件被检查到木马

### ISSUE THREAD

**Issue by at3110027** [zoujingli/ThinkAdmin#210]
![image](https://user-images.githubusercontent.com/44117856/67486958-9ade3e80-f69f-11e9-9148-e64f80b80652.png)

请问你项目代码文件中 ThinkAdmin-master/application/admin/queue/task/bin/ThinkAdmin.exe 这个文件被windows 自带杀毒软件检测到木马，这个文件是做什么用？为什么在会有exe文件？

**Comment by zhongshaofa** [comment]
应该是windows上的队列推送服务

**Comment by zoujingli** [comment]
后台进程文件，需要信任下

**Comment by zoujingli** [comment]
已经更换 RunHiddenConsole.exe 文件，再测试下会不会报不安全？
