### ISSUE TITLE
请问上传文件是怎么配置和写的？

### ISSUE THREAD

**Issue by im286er** [zoujingli/ThinkAdmin#213]
可能我说的比较笼统，就是自己建了一个新的模块，输入页面有个按钮就是上传的，用的layui的上传模块，但是怎么使用本系统自带的上传功能，还是得用tp的自己重写？

**Comment by zoujingli** [comment]
已经写好，只要加一个按钮就行
data-file=one data-type=jpg,png data-uptype='local'
