### ISSUE TITLE
操作的时候，提示表单令牌验证失败

### ISSUE THREAD

**Issue by silentlytao** [zoujingli/ThinkAdmin#217]
在library\tools\Csrf类中72行，使用了session前缀为csrf
而在library\service\TokenService类47行，未使用session前缀csrf读取token的值
导致cache无数据，始终验证失败，请及时修复

**Comment by aven-li** [comment]
/**
     * 检查表单令牌验证
     * @param boolean $return 是否返回结果
     * @return boolean
     */
    protected function applyCsrfToken($return = false)
    {
        return Csrf::checkFormToken();
//        return TokenHelper::instance()->init($return);
    }
改成csrf检测token就行

**Comment by aven-li** [comment]
protected function applyCsrfToken($return = false)
    {
        return Csrf::checkFormToken();
    }

改成csrf token 检测就行

**Comment by zoujingli** [comment]
无防，72 只是生成 token，带了 csrf 前缀，Csrf 类已经放弃，需要调用 TokenService::checkFormToken 实现检查，后面有更新 systoken 方法的
