### ISSUE TITLE
菜单修改的时候图标读取失败问题

### ISSUE THREAD

**Issue by laijianbo** [zoujingli/ThinkAdmin#219]
后台添加cai'd菜单后再修改，发现图标无法正常读取，原因是获取菜单数据的时候少查询了一个字段“icon”。
![image](https://user-images.githubusercontent.com/10562738/70599443-1d0ecc00-1c28-11ea-9e4d-dc648a66fa09.png)
修复：application/admin/controller/Menu.php第101行添加字段“icon”即可
![image](https://user-images.githubusercontent.com/10562738/70599586-6ced9300-1c28-11ea-8946-049a6ac19a67.png)

**Comment by zoujingli** [comment]
是哪个版本？

**Comment by zoujingli** [comment]
已经修复
