### ISSUE TITLE
mimes.php中对于不同操作系统的兼容问题

### ISSUE THREAD

**Issue by newcou** [zoujingli/ThinkAdmin#51]
经测发现mac端对docx等office07以上格式无法识别，即不能选择文件
zip格式弹出框非常缓慢，约8秒
简单修改zip为'zip'   => [ 'multipart/x-zip'],秒开

本人对mimetype不大熟悉，还请作者百忙之中完善下mime的格式

**Comment by zoujingli** [comment]
之前的mime是来看CI框架，有空我会更新的，Thanks

**Comment by zoujingli** [comment]
新版本的ext节能mine来自网络，会动态更新缓存在本地，可以参考新本地的 fileService 进行修改下
