### ISSUE TITLE
Think.Admin很不错,但是缺少一些常用功能

### ISSUE THREAD

**Issue by qiacou** [zoujingli/ThinkAdmin#52]
Think.Admin缺少后台数据库备份/还原 ,sql提交等常用功能 ,希望完善哦 .Think.Admin 已经很不错了 加油

**Comment by zoujingli** [comment]
数据库操作，下个大版本会加上

**Comment by zoujingli** [comment]
数据库操作存在太多安全问题，建议放到服务器管理当中去处理
