### ISSUE TITLE
微信对接成功，但是发送关键字提示服务器故障！

### ISSUE THREAD

**Issue by LaoHuCai** [zoujingli/ThinkAdmin#83]
zou大好，您的ThinkAdmin系统非常好用，今天测试微信的对接发现一个问题，公众平台已经对接成功，但是通过微信发送关键字查询，得到服务器故障提示，请问如何解决，谢谢

**Comment by LaoHuCai** [comment]
补一个Log：
POST /wechat/api.push/notify.html?signature=00e3b8624b01683f4aec573731a1cdd7f585&timestamp=1521775758&nonce=765521452&openid=oyJ03wejAukgjhfijgaZhHf7N1jE&encrypt_type=aes&msg_signature=de1d77jh964356fd2da06329bd7d52a8a47cdfd
[ error ] [0]variable type error： boolean[\thinkphp\library\think\Response.php:385]

**Comment by zoujingli** [comment]
已修改，不再使用return xml, 直接使用客服消息处理
