### ISSUE TITLE
推送图文，客户端收到的是空白

### ISSUE THREAD

**Issue by LaoHuCai** [zoujingli/ThinkAdmin#84]
zou大，非常感谢您上次及时的问题处理，辛苦了，今天更新您的程序，发现推送的图文消息客户端收到的是空白，请问我应该如何处理，谢谢

**Comment by zoujingli** [comment]
此周期测试号已经无法推荐消息，下个月再进一步跟进，谢谢反馈！

**Comment by LaoHuCai** [comment]
辛苦了，zou大

**Comment by zoujingli** [comment]
已修复此问题，更新 MediaService 即可

**Comment by LaoHuCai** [comment]
辛苦了，谢谢
