### ISSUE TITLE
请问在button上的onclick函数里怎样处理才能阻止open-modal打开页面

### ISSUE THREAD

**Issue by MrYuLei** [zoujingli/ThinkAdmin#85]
<button data-modal='{:url("$classuri/index")}' href="javascript:void(0)" onclick="return check_order();" class='layui-btn layui-btn-small layui-btn-danger' >
        <i class='fa fa-plus'></i> 首页
    </button>

<scritp>

function check_order(){
     //此处应该如何处理?........
}
</script>

**Comment by zoujingli** [comment]
button type='button'

**Comment by zoujingli** [comment]
data-modal
data-open
data-load
不要出现到标签上

**Comment by MrYuLei** [comment]
好的，谢谢啦~~~
