### ISSUE TITLE
后台图片上传插件，多次添加图片然后上传，之前添加的图片会重复上传，请问这个怎么解决？

### ISSUE THREAD

**Issue by MrYuLei** [zoujingli/ThinkAdmin#86]
@zoujingli 
![1](https://user-images.githubusercontent.com/33047708/37898198-c2185752-311a-11e8-8b82-41b82e002349.png)

**Comment by zoujingli** [comment]
新版本的可以直接使用JS调用
$('input').uploadMultipleImage()

**Comment by MrYuLei** [comment]
我这是旧版本的，新版本如何升级？只需要将插件替换就行了吗？
