### ISSUE TITLE
DataService.php 中一处关于database prefix 处理的错误

### ISSUE THREAD

**Issue by goldeagle** [zoujingli/ThinkAdmin#87]
在 DataService::save 方法中，Db::name($db->getTable()) 应用的时候，如果系统配置中设置了数据表前缀，则此处会两次调用前缀，因为 getTable() 方法是返回前缀的，而 DB:name 方法会再次添加前缀，应该修改为 DB::table($db->getTable()) 这种无前缀的处理方式。

**Comment by zoujingli** [comment]
感谢反馈，我会改为::table方法

**Comment by zoujingli** [comment]
已处理
