### ISSUE TITLE
问一下，商城产品页面。logo上传问题

### ISSUE THREAD

**Issue by jackiezyb** [zoujingli/ThinkAdmin#89]
商城产品页面， 点击logo上传， 界面闪退，但是文件传输成功了，界面也没有任何显示， 点击编辑也是默认图片，不会显示上传的，但是查看数据库有对应图片的路径，问一下咋修改呀？谢谢

**Comment by zoujingli** [comment]
请提供下环境信息，我这里测试是没有问题的

**Comment by jackiezyb** [comment]
或者告知一下你的运行环境也可以， 谢谢

**Comment by jackiezyb** [comment]
// 上传单个图片
    $.fn.uploadOneImage = function () {
        var name = $(this).attr('name') || 'image';
        var type = $(this).data('type') || 'png,jpg';
        var $tpl = $('<a data-file="one" data-field="' + name + '" data-type="' + type + '" class="uploadimage"></a>');
        $(this).hide().attr('name', name).after($tpl).on('change', function () {
            $tpl.get(0).style = this.value ? 'background-image:url(' + this.value + ')' : '';
        }).trigger('change');
    };
查了一下应该是这里出的问题，多图没有问题，单图却不行

**Comment by zoujingli** [comment]
当前页面打开了几层弹出框

**Comment by jackiezyb** [comment]
你可以自己测试一下，goods/product/index, 添加商品，logo文件上传成功，但是无法显示预览（php 5.x和php 7.0 都是这样的），文件上传都是弹出一个窗口，单文件上传后估计是没有刷新造成的。多文件上传没有问题。

**Comment by anyons** [comment]
我这里测试是正常的，http://demo.thinkadmin.top
再问是，你是什么浏览器
